{
 "title": "Prometheus Pika Exporter",
 "tags": [
  "prometheus",
  "pika"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(pika_server_info, job)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(pika_server_info{job=~'$job'},group)"
   },
   {
    "name": "instance",
    "label": "Collect Instance",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group'}, instance)"
   },
   {
    "name": "addr",
    "label": "Pika Server Addr",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group'}, addr)"
   },
   {
    "name": "alias",
    "label": "Pika Server Alias",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, alias)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, role)"
   },
   {
    "name": "serverid",
    "label": "Server ID",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, server_id)"
   },
   { "name": "codis_proxy", "label": "Codis Proxy", "query": { "query": "label_values(proxy_qps,addr)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pika Build Info List",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "pika_build_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Pika Server Info List",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Base Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Build Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "pika_build_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Server Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_uptime_in_seconds{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Tread Num",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_thread_num{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Sync Thread Num",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_sync_thread_num{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Total Connections Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_total_connections_received{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_total_commands_processed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Total number of commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_calls{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Total milliseconds of the command",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_usec{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Average milliseconds of the command time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_usec_per_call{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_connected_clients{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "connected-clients"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(pika_used_cpu_sys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m]) + irate(pika_used_cpu_user{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m])) * 100",
     "legendFormat": "cpu-usage"
    }
   ]
  },
  {
   "title": "CPU Usage Children",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(pika_used_cpu_sys_children{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m]) + irate(pika_used_cpu_user_children{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m])) * 100",
     "legendFormat": "cpu-usage-children"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_used_memory{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "used-memory"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_db_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "compression-{{compression}}"
    }
   ]
  },
  {
   "title": "DB Memtable Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_db_memtable_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "db-memtable-usage"
    },
    {
     "expr": "pika_db_tablereader_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "db-tablereader-usage"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_log_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "log_size"
    }
   ]
  },
  {
   "title": "Commands Processed in per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pika_total_commands_processed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[5m])",
     "legendFormat": "commands-processed/sec"
    }
   ]
  },
  {
   "title": "The number of Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Role",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Connected Slaves",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 5, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_connected_slaves{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "connected-slaves"
      }
     ]
    },
    {
     "title": "Connected Slave List",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "pika_slave_lag{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Master Link Status",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_master_link_status{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{master_host}} {{master_port}}"
      }
     ]
    },
    {
     "title": "Slave Priority",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_slave_priority{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{master_host}} {{master_port}}"
      }
     ]
    },
    {
     "title": "Binlog Offset",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_binlog_offset_db{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "Binlog Offset Filenum",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_binlog_offset_filenum_db{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{db}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time-consuming operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scan Keyspace",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "pika_is_scaning_keyspace{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Bgsave",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "pika_is_bgsaving{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Compact",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "pika_compact{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Keys Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Keys",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}} {{db}} "
      }
     ]
    },
    {
     "title": "Expire Keys",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_expire_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}} {{db}} "
      }
     ]
    },
    {
     "title": "Invalid Keys",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_invalid_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}} {{db}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Net Input Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_total_net_input_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Instantaneous Input Kbps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "KiBs" }
     ],
     "targets": [
      {
       "expr": "pika_instantaneous_input_kbps{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{ addr }}"
      }
     ]
    },
    {
     "title": "Total Net Output Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_total_net_output_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Instantaneous Output Kbps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "KiBs" }
     ],
     "targets": [
      {
       "expr": "pika_instantaneous_output_kbps{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{ addr }}"
      }
     ]
    },
    {
     "title": "Total Net Replication Input Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_total_net_repl_input_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Instantaneous Input Replication Kbps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "KiBs" }
     ],
     "targets": [
      {
       "expr": "pika_instantaneous_input_repl_kbps{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{ addr }}"
      }
     ]
    },
    {
     "title": "Total Net Replication Output Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_total_net_repl_output_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Instantaneous Output Replication Kbps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "KiBs" }
     ],
     "targets": [
      {
       "expr": "pika_instantaneous_output_repl_kbps{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{ addr }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memtable Flush Pending",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bool" }
     ],
     "targets": [
      {
       "expr": "pika_mem_table_flush_pending{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Immutable MemTable",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_num_immutable_mem_table{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Immutable Memtable Flushed",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_num_immutable_mem_table_flushed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Running Flushes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_num_running_flushes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Cur Size Active Memtable",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_cur_size_active_mem_table{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Cur Size All Memtables",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_cur_size_all_mem_tables{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Size All Memtables",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_size_all_mem_tables{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Block Cache Capacity",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_block_cache_capacity{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Block Cache Usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_block_cache_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Block Cache Pinned Usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_block_cache_pinned_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Is Compaction Pending",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bool" }
     ],
     "targets": [
      {
       "expr": "pika_compaction_pending{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Running Compactions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 46 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_num_running_compactions{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Total SST Files Size",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_total_sst_files_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Live SST Files Size",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_live_sst_files_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Blob Files",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_num_blob_files{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Blob Stats",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_blob_stats{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Total Blob File Size",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_total_blob_file_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Live Blob File Size",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_live_blob_file_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Estimate Live Data Size",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_estimate_live_data_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Estimate Table Readers Mem",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 72 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_estimate_table_readers_mem{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Estimate Num Keys",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_estimate_num_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Estimate Pending Compaction Bytes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 72 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_estimate_pending_compaction_bytes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Background Errors",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_background_errors{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Current Super Version Number",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 85 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_current_super_version_number{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Live Versions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_num_live_versions{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    },
    {
     "title": "Snapshots",
     "type": "graph",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_num_snapshots{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "{{data_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Codis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Codis proxy qps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "proxy_qps{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Command max delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "proxy_max_delay{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{opstr}}"
    }
   ]
  },
  {
   "title": "Proxy total slow cmd",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "proxy_total_slow_cmd{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Proxy online",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 57 },
   "yaxes": [
    { "format": "bool_yes_no" }
   ],
   "targets": [
    {
     "expr": "proxy_online{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Pproxy rusage mem ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "proxy_rusage_mem{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Proxy rusage cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "proxy_rusage_cpu{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "proxy_usecs_percall",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(proxy_usecs_percall{cluster_name=\"$cluster_name\",port=~\"$port\", dc=~\"$dc\", role=~\"$role\", ip=~\"$ip\"})by(addr,proxy_id)",
     "legendFormat": "{{opstr}}"
    }
   ]
  },
  {
   "title": "proxy usecs percall",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 71 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "proxy_usecs_percall{addr=~\"$codis_proxy\"}",
     "legendFormat": "{{opstr}}"
    }
   ]
  }
 ]
}